version: 1
formatters:
  mainFormatter:
    format: '%(asctime)s [%(levelname)s] -> %(name)s: %(message)s'
  modulesFormatter:
    format: '%(asctime)s [%(levelname)s] -> %(module)s(%(funcName)s): %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: mainFormatter
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: modulesFormatter
    filename: logs/connettore.log
    when: W0
    interval: 1


loggers:
  log:
    level: INFO
    handlers: [file, console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]